version: '3'

services:
  app:
    container_name: app
    entrypoint:
      - /bin/sh
      - -c
      - |
        chmod +x ./start.sh && \
        wait-for db:5432 -t 40 -- ./start.sh
    tty: true
    build:
      context: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - 5000:5000
      - 3000:3000
      - 3001:3001
      - 9229:9229
    networks:
      - nodenetwork
    depends_on:
      - db
      - azurite
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - nodenetwork
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azureStorage
    restart: always
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    networks:
      - nodenetwork
volumes:
  pgdata:


networks:
  nodenetwork:
    name: nodenetwork
    driver: bridge
